### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler

### ISSUE THREAD

**Issue by ETGgames** [mongodb/stitch-ios-sdk#93]
Please add swift 4.2 support

**Comment by jsflax** [comment]
Hi @ETGgames ,

This should now be fixed, with the release of StitchCoreSDK 4.0.6. Please give it a try.

Thanks!

**Comment by ETGgames** [comment]
There is this error when trying to update the pods
Traceback (most recent call last):
  File "scripts/build_frameworks.py", line 1, in <module>
    from frameworkify import (
  File "/Users/ethansarif-kattan/Library/Caches/CocoaPods/Pods/Release/StitchCoreSDK/4.0.5-c11f3/scripts/frameworkify/__init__.py", line 1, in <module>
    from modules import Module, SwiftModule
ModuleNotFoundError: No module named 'modules'

**Comment by jsflax** [comment]
Have you tried clearing your cache?

What does your podfile look like?

**Comment by ETGgames** [comment]
Tried cleaning the cache, still get the same error. This is my podfile:

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoppelChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoppelChat
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'IQKeyboardManagerSwift'
  #pod 'SwiftyJSON'
  pod 'Cosmos'
  #pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
  pod 'SwiftyStoreKit'
  pod 'Disk'
  pod 'Fabric', '~> 1.7.7'
  pod 'Crashlytics', '~> 3.10.2'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  pod 'NVActivityIndicatorView'
  pod 'AWSMobileClient'
  pod 'AWSRekognition'
  #pod 'RangeSeekSlider' - done manually
  pod 'StitchSDK'

  
  target 'DoppelChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoppelChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
#
#post_install do |installer|
#	installer.pods_project.targets.each do |target|
#		target.build_configurations.each do |config|
#			config.build_settings.delete('CODE_SIGNING_ALLOWED')
#			config.build_settings.delete('CODE_SIGNING_REQUIRED')
#		end
#	end
#	installer.pods_project.build_configurations.each do |config|
#		config.build_settings.delete('CODE_SIGNING_ALLOWED')
#		config.build_settings.delete('CODE_SIGNING_REQUIRED')
#	end
#end
